DjangoProject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
class HomeView(TemplateView):
    template_name = 'home.html'  

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('item/', include('item.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

item/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.item_create,name='item_create'),
    path('item/<int:pk>/', views.item_detail, name='item_detail'),
    path('item/<int:item_id>/update/', views.item_update, name='item_update'),
    path('item/list', views.item_list_view, name='item_list'),
    path('item/stock/<int:item_id>/', views.item_stock_view, name='item_stock_view'),
    path('item/search/', views.search_form, name='search_form'),
    path('searchresult/', views.search_results, name='search_results'),


    path('itemreceipt/create', views.itemreceipt_create, name='itemreceipt_create'),
    path('itemreceipt/update/<int:pk>/', views.itemreceipt_update, name='itemreceipt_update'),
    path('itemreceipt/list/', views.itemreceiptinfo_list, name='itemreceiptinfo_list'),
    path('itemreceipt/delete/<int:pk>/', views.itemreceiptinfo_delete, name='itemreceiptinfo_delete'),
    
    
    path('itemdelivery/create', views.itemdelivery_create, name='itemdelivery_create'),
    path('itemdelivery/update/<int:pk>/', views.itemdelivey_update, name='itemdelivey_update'),
    path('itemdelivery/list/', views.itemdeliveryinfo_list, name='itemdeliveryinfo_list'),
    path('itemdelivery/delete/<int:pk>/', views.itemdeliveryinfo_delete, name='itemdeliveryinfo_delete'),
    
    path('salesorder/create/', views.salesorder_create, name='salesorder_create'),
    path('salesorder/update/<int:pk>/', views.salesorder_update, name='salesorder_update'),
    path('salesorder/list/', views.salesorder_info_list, name='salesorder_info_list'),
    path('salesorder/delete/<int:pk>/', views.salesorder_info_delete, name='salesorder_info_delete'),
    
    path('warehouses/create/', views.warehouse_create, name='warehouse_create'),
    path('currency/create/', views.currency_create, name='currency_create'),
    path('unit/create/', views.unit_create, name='unit_create'),


    path('business_partner/create/', views.business_partner_create, name='business_partner_create'),

    path('stock/create/', views.stock_create, name='stock_create'),


]

item/models.py
from os import name
from django.db import models
from django.utils import timezone
from django.core.exceptions import ValidationError

class Currency(models.Model):
    name = models.CharField(max_length=100,unique=True)
    code = models.CharField(max_length=3)

    def __str__(self):
        return self.name
    
class Unit(models.Model):
    name=models.CharField(max_length=100,unique=True)

    def __str__(self):
        return self.name

class Warehouse(models.Model):
    name = models.CharField(max_length=100,unique=True)
    location = models.CharField(max_length=100)
    # Add any other fields for the Warehouse model

    def __str__(self):
        return self.name
class BusinessPartner(models.Model):
    code = models.CharField(max_length=50,unique=True)
    name = models.CharField(max_length=100,unique=True)
    address = models.TextField()
    currency = models.ForeignKey(Currency, on_delete=models.PROTECT,default=1)

    CURRENCY_TYPES = [
        ('local', 'Local Currency'),
        ('foreign', 'Foreign Currency'),
    ]
    currency_type = models.CharField(max_length=10, choices=CURRENCY_TYPES,default='local')

    VENDOR_TYPES = [
        ('supplier', 'Supplier'),
        ('customer', 'Customer'),
    ]
    vendor_type = models.CharField(max_length=10, choices=VENDOR_TYPES,default='customer')

    def __str__(self):
        return self.name  
    
    
class Item(models.Model):
    name = models.CharField(max_length=100,unique=True)
    description = models.TextField()
    quantity = models.PositiveIntegerField()
    warehouse = models.ForeignKey(Warehouse, on_delete=models.CASCADE,default=1)
    unit = models.ForeignKey(Unit, on_delete=models.SET_DEFAULT, default=1)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    
    # Add any other fields you need

    def __str__(self):
        return self.name
class Stock(models.Model):
    warehouse = models.ForeignKey(Warehouse, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)

 
class ItemReceiptinfo(models.Model):
    warehouse = models.ForeignKey(Warehouse, on_delete=models.CASCADE)
    docno = models.PositiveIntegerField(default=1,unique=True)
    created = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return f" {self.docno}"
        
class ItemReceipt(models.Model):
    item_info = models.ForeignKey(ItemReceiptinfo, on_delete=models.CASCADE, null=True, default=None)
    warehouse = models.ForeignKey(Warehouse, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    def __str__(self):
        return f" {self.item_info.docno}"

    def clean(self):
        if self.quantity == 0:
            raise ValidationError("Quantity cannot be 0.")
 
class ItemDeliveryinfo(models.Model):
    warehouse = models.ForeignKey(Warehouse, on_delete=models.CASCADE)
    docno = models.PositiveIntegerField(default=1,unique=True)
    created = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return f" {self.docno}" 
  
class ItemDelivery(models.Model):
    item_info = models.ForeignKey(ItemDeliveryinfo, on_delete=models.CASCADE, null=True, default=None)    
    warehouse = models.ForeignKey(Warehouse, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    def __str__(self):
        return f"ItemDelivery: {self.item.name} - {self.quantity}"

class SalesOrderInfo(models.Model):
    order_number = models.PositiveIntegerField(default=1, unique=True)
    customername = models.ForeignKey(BusinessPartner,on_delete=models.CASCADE,null=True, default=None)
    created = models.DateTimeField(default=timezone.now)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2, editable=False)



    def __str__(self):
        return f"SalesOrderInfo: {self.order_number}"
    
    
class SalesOrderDelivery(models.Model):
    order_info = models.ForeignKey(SalesOrderInfo, on_delete=models.CASCADE, null=True, default=None)

    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    price_total = models.DecimalField(max_digits=10, decimal_places=2, editable=False)



    def __str__(self):
        return f"SalesOrderDelivery: {self.item.name} - {self.quantity}"





    

item/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse


from django.core.exceptions import ValidationError
from django.forms import formset_factory, inlineformset_factory
from .models import ItemReceipt, ItemReceiptinfo,ItemDeliveryinfo,ItemDelivery,SalesOrderInfo,SalesOrderDelivery,Stock
from .forms import ItemReceiptinfoForm,ItemReceiptForm,ItemDeliveryinfoForm,ItemDeliveryForm,SalesOrderInfoForm,SalesOrderDeliveryForm,StockForm


from django.contrib import messages
from django.db.models import Q

from .forms import UnitForm
from .models import Unit

from .forms import CurrencyForm
from .models import Currency


from .forms import ItemForm,SearchForm
from .models import Item

from .models import Warehouse
from .forms import WarehouseForm


from .models import BusinessPartner
from .forms import BusinessPartnerForm

from django.db.models import Sum
from .models import  Stock, ItemReceipt, ItemDelivery




def currency_create(request):
    # Retrieve the success message from the query parameters
    success_message = request.GET.get('success_message')
    if request.method == 'POST':
        form = CurrencyForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'The post has been created successfully.')
            return redirect('currency_create')
    else:
        form = UnitForm()
        

    return render(request, 'item/currency/currency_create.html', {'form': form})

def unit_create(request):
    # Retrieve the success message from the query parameters
    success_message = request.GET.get('success_message')
    if request.method == 'POST':
        form = UnitForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'The post has been created successfully.')
            return redirect('unit_create')
    else:
        form = UnitForm()
        

    return render(request, 'item/unit/unit_create.html', {'form': form})


def warehouse_create(request):
    # Retrieve the success message from the query parameters
    success_message = request.GET.get('success_message')
    if request.method == 'POST':
        form = WarehouseForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'The post has been created successfully.')
            return redirect('warehouse_create')
    else:
        form = WarehouseForm()
        

    return render(request, 'item/warehouse/warehouse_create.html', {'form': form})

def stock_create(request):
    success_message = request.GET.get('success_message')

    if request.method == 'POST':
        form = StockForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'The stock has been created successfully.')
            return redirect('stock_create')
    else:
        form = StockForm()
        context = {'form': form,'page_title': 'Create Stock'}

    return render(request, 'item/create.html',context )



def item_create(request):
    warehouses = Warehouse.objects.all()
    units = Unit.objects.all()
    if request.method == 'POST':
        form = ItemForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'The post has been created successfully.')
            return redirect('item_create')
        else:
            error_messages = form.errors.values()
            for message in error_messages:
                messages.error(request, message)        
    else:
        warehouses = Warehouse.objects.all()
        units = Unit.objects.all()
        form = ItemForm()
    
    return render(request, 'item/item_create.html', {'form': form,'warehouses': warehouses,'units':units})

def item_update(request, item_id):
    item = get_object_or_404(Item, pk=item_id)
    warehouses = Warehouse.objects.all()
    units = Unit.objects.all()
    
    if request.method == 'POST':
        form = ItemForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            messages.success(request, 'The item has been updated successfully.')
            return redirect('item_detail', pk=item.id)
    else:
        form = ItemForm(instance=item)
    
    return render(request, 'item/item_create.html', {'form': form, 'item': item, 'warehouses': warehouses, 'units': units})

def search_form(request):

    form = SearchForm(request.POST)
    context = {
        'form': form,
    }
    return render(request, 'item/search_form.html',context)
    
def search_results(request):
    name = request.GET.get('name')
    description = request.GET.get('description')

    results = Item.objects.filter(
        Q(name__icontains=name) 
        # Add more conditions for other columns as necessary
    )
    if results.count() == 1:
        item = results.first()
        form = ItemForm(instance=item)
        return render(request, 'item/item_detail.html', {'form': form, 'item': item})

    return render(request, 'item/search_results.html', {'results': results})

def item_detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    form = ItemForm(instance=item)
    return render(request, 'item/item_detail.html', {'form': form,'item': item})


def item_list_view(request):
    items = Item.objects.all()

    context = {
        'items': items,
    }

    return render(request, 'item/item_list.html', context)


def item_stock_view(request, item_id):
    item = Item.objects.get(id=item_id)
    warehouses = Warehouse.objects.all()

    


    item_quantities = []
    for warehouse in warehouses:
        stock_quantity = Stock.objects.filter(warehouse=warehouse, item=item).aggregate(Sum('quantity'))['quantity__sum'] or 0
        receipt_quantity = ItemReceipt.objects.filter(warehouse=warehouse, item=item).aggregate(Sum('quantity'))['quantity__sum'] or 0
        delivery_quantity = ItemDelivery.objects.filter(warehouse=warehouse, item=item).aggregate(Sum('quantity'))['quantity__sum'] or 0

        total_quantity = stock_quantity + receipt_quantity - delivery_quantity

        item_quantities.append({
            'warehouse': warehouse,
            'quantity': total_quantity,
        })

    context = {
        'item': item,
        'item_quantities': item_quantities,

        
    }

    return render(request, 'item/item_detail_stock.html', context)


def business_partner_create(request):
    if request.method == 'POST':
        form = BusinessPartnerForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'The post has been created successfully.')
            return redirect('business_partner_create')
    else:
        currencies = Currency.objects.all()
        form = BusinessPartnerForm()
    return render(request, 'item/business_partner/business_partner_create.html', {'form': form,'currencies': currencies})

def itemreceipt_create(request):
    ItemReceiptFormSet = inlineformset_factory(
        ItemReceiptinfo,
        ItemReceipt,
        form=ItemReceiptForm,
        fields=('item', 'quantity'),
        extra=0,
        can_delete=False,
        min_num=1,
        validate_min=True
    )

    if request.method == 'POST':
        form = ItemReceiptinfoForm(request.POST)
        formset = ItemReceiptFormSet(request.POST)

        if form.is_valid() and formset.is_valid():
            # Get the last inserted ItemReceiptinfo
            last_item_receiptinfo = ItemReceiptinfo.objects.last()

            # Calculate the new docno
            if last_item_receiptinfo:
                new_docno = last_item_receiptinfo.docno + 1
            else:
                new_docno = 1

            # Save the form with the new docno
            itemreceiptinfo = form.save(commit=False)
            itemreceiptinfo.docno = new_docno
            itemreceiptinfo.save()

            for formset_form in formset.forms:
                item_receipt = formset_form.save(commit=False)
                item_receipt.item_info = itemreceiptinfo
                item_receipt.warehouse = itemreceiptinfo.warehouse
                item_receipt.save()

            messages.success(request, 'The post has been created successfully.')
            return redirect('itemreceipt_create')
        else:
            # Add form errors to messages framework
            for field, error_list in form.errors.items():
                for error in error_list:
                    messages.error(request, f'{field}: {error}')

            for formset_error in formset.non_form_errors():
                messages.error(request, formset_error)

    else:
        form = ItemReceiptinfoForm()
        formset = ItemReceiptFormSet()

    context = {
        'form': form,
        'formset': formset,
        'page_title': 'Create Item Receipt'  # Set the page title here
    }
    return render(request, 'item/itemreceipt/form.html', context)




def itemreceipt_update(request, pk):
    # Retrieve the success message from the query parameters
    success_message = request.GET.get('success_message')
    itemreceiptinfo = get_object_or_404(ItemReceiptinfo, pk=pk)
    ItemReceiptFormSet = inlineformset_factory(
        ItemReceiptinfo,
        ItemReceipt,
        form=ItemReceiptForm,
        fields=('item', 'quantity'),
        extra=1,
        can_delete=False,
        min_num=1,
        validate_min=True
    )

    if request.method == 'POST':
        form = ItemReceiptinfoForm(request.POST, instance=itemreceiptinfo)
        formset = ItemReceiptFormSet(request.POST, instance=itemreceiptinfo)

        if form.is_valid() and formset.is_valid():
            form.save()
            
            for formset_form in formset.forms:
                if formset_form.has_changed():
                    item_receipt = formset_form.save(commit=False)
                    item_receipt.item_info = itemreceiptinfo
                    item_receipt.warehouse = itemreceiptinfo.warehouse

templates/item/create.html
{% extends 'base.html' %}
{% block content %}


  <div class="col-md-12">
	
    <div class="card">
		<div class="card-body">
		  <h2 class="font-weight-bold my-2 text-center mb-2 mt-2 font-weight-bold">
			  <strong>{{ page_title }}</strong>
			</h2>
			<hr>
			{% include 'alert.html' %}
			<!-- Success message -->
<!-- Success message -->
<form method="post">
  {% include 'component/formfield.html' %}
  

	  <div class="text-center">
		<button type="submit" class="btn blue-gradient btn-rounded waves-effect waves-light">Save</button>
	  </div>
	  
</form>
</div>
</div>
</div>

{%endblock  %}

templates/item/item_create.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


  <div class="col-md-12">
  

    <div class="card">
      <div class="card-body">
        <h2 class="font-weight-bold my-2 text-center mb-2 mt-2 font-weight-bold">
            <strong>Item Master Data</strong>
          </h2>
          <hr>
          

          <a href="{% url 'item_list' %}"> <img src="{% static 'images/list-50.png' %}" alt="Item List "> </a> 
          <a href="{% url 'search_form' %}"> <img src="{% static 'images/search-50.png' %}" alt="Item Search "></a>
          <a href="{% url 'item_create' %}"> <img src="{% static 'images/add-50.png' %}" alt="Item Add "></a>
          {% include 'alert.html' %}
      <!-- Success message -->
<form method="post">
  {% csrf_token %}
  {% include 'component/formfield3col.html' %}
  



    <div class="text-center">
      <button type="submit" class="btn blue-gradient btn-rounded waves-effect waves-light">Save</button>
    </div>

</form>

</div>
</div>
</div>

  {%endblock  %}

templates/item/item_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


  <div class="col-md-12">

    <div class="card">
      <div class="card-body">
        <h2 class="font-weight-bold my-2 text-center mb-2 mt-2 font-weight-bold">
          <strong>Item Details </strong>
        </h2>
        <a href="{% url 'item_stock_view' item_id=item.id %}"><img src="{% static 'images/stock-25.png' %}" alt="Item Stock "> </a>
        <hr>
     

<h2>{{ item.name }}</h2>


<form method="POST" action="{% url 'item_update' item.pk %}">

    {% csrf_token %}
    {{ form.as_p }}
    <div class="text-center">
      <button type="submit" class="btn blue-gradient btn-rounded waves-effect waves-light">Save</button>
    </div>
  </form>


</div>
</div>
</div>

  {%endblock  %}

templates/item/item_detail_stock.html
{% extends 'base.html' %}

{% block content %}


  <div class="col-md-12">

    <div class="card">
      <div class="card-body">
<h1>{{ item.name }}</h1>

<h2>Item Quantities</h2>
{{ stock.inhand }}
<table class="table table-bordered border-primary">
  <thead>
    <tr>
      <th>Warehouse</th>
      <th>Quantity</th>
    </tr>
  </thead>
  <tbody>
    {% for item_quantity in item_quantities %}
      <tr>
        <td>{{ item_quantity.warehouse.name }}</td>
        <td>{{ item_quantity.quantity }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>


    
</div>
</div>
</div>

  {%endblock  %}

templates/item/item_list.html
{% extends 'base.html' %}
{% block content %}


  <div class="col-md-12">

    <div class="card">
      <div class="card-body">

<h1> All Items </h1>

<ul>
  {% for item in items %}
    <li>{{ item.name }}</li>
  {% endfor %}
</ul>


</div>
</div>
</div>

  {%endblock  %}

templates/item/search_form.html
{% extends 'base.html' %}
{% block content %}


  <div class="col-md-12">

    <div class="card">
      <div class="card-body">


<!-- search_form.html -->
<form method="GET" action="{% url 'search_results' %}">
      <div class="form-group">
        <label for="id_name">Name:</label>
        {{ form.name }}
      </div>
      <div class="form-group">
        <label for="id_description">Description:</label>
        {{ form.description }}
      </div>
  
    <div class="text-center">
      <button type="submit" class="btn blue-gradient btn-rounded waves-effect waves-light">Find</button>
    </div>
  </form>

</div>
</div>
</div>

  {%endblock  %}

templates/item/search_results.html
{% extends 'base.html' %}

{% block content %}


  <div class="col-md-12">

    <div class="card">
      <div class="card-body">

<!-- search_results.html -->
{% for item in results %}
  <h3>{{ item.name }}</h3>
  <p>{{ item.description }}</p>
  <a href="{% url 'item_detail' item.pk %}">View</a>
  <!-- Display other fields as necessary -->
{% empty %}
  <p>No results found.</p>
{% endfor %}

</div>
</div>
</div>

  {%endblock  %}

templates/item/warehouse_create.html
{% extends 'base.html' %}
{% block content %}


  <div class="col-md-12">
	{% if messages %}
		<div class="messages">
		{% for message in messages %}
			<div class="alert {% if message.tags %}alert-{{ message.tags }}"{% endif %}>
				{{ message }}
			</div>
		{% endfor %}
		</div>
	{% endif %}
<!-- Success message -->
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit">
</form>
</div>

{%endblock  %}